# Generated by Django 5.0.4 on 2024-05-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Boxing', 'Boxing'), ('Thai Boxing', 'Thai Boxing'), ('BJJ', 'BJJ'), ('Private Training', 'Private Training'), ('Group Training', 'Group Training'), ('Events', 'Events'), ('Corporate Events', 'Corporate Events'), ('Kids Classes', 'Kids Classes')], max_length=100, unique=True),
        ),
    ]
