# Generated by Django 5.0.4 on 2024-05-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_trainingsession_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='categories',
            field=models.ManyToManyField(related_name='training_sessions', to='activities.category'),
        ),
    ]
