# Generated by Django 5.0.4 on 2024-05-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_create_categories'),
        ('activities', '0005_category_trainingsession_categories'),
    ]

    operations = [
    ]
