# Generated by Django 5.0.4 on 2024-05-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_merge_20240528_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Boxing', 'Boxing'), ('Thai Boxing', 'Thai Boxing'), ('BJJ', 'BJJ'), ('Private Training', 'Private Training'), ('Group Training', 'Group Training'), ('Events', 'Events'), ('Corporate Events', 'Corporate Events'), ('Children Classes', 'Children Classes')], max_length=100, unique=True),
        ),
    ]
