# Generated by Django 5.0.4 on 2024-05-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
